Fixed bug in drift search. Under python 3.12.3 we get TypeError: AsyncCompletions.create() got an unexpected keyword argument 'model_params' Changed from **llm_kwargs  to model_params.